spring.application.name=driver-vehicle-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_driver_vehicle}
spring.data.mongodb.database=ridelink_driver_vehicle

server.port=8082
